# include = ["**/*.toml", ]
# exclude = [
#   "**/*nested-1000.toml",
#   "**/node_modules/**",
#   "**/invalid/*",
#   "test-data/analytics/**",
# ]

[[rule]]
# include = ["**/Cargo.toml"]
# keys = ["dependencies", "*-dependencies"]

[rule.formatting]
align_entries         = true
compact_entries       = false
compact_inline_tables = false
indent_string         = "    "
reorder_keys          = true
# indent_tables = true
reorder_arrays = true
# indent_entries = true
